version: '3.5'
services:
  postgres:
    volumes:
      - ../psqlData:/var/lib/postgresql/data # change the path to yours accordingly
  graphdb:
    volumes:
      - ../graphdbData:/opt/graphdb/home
  mongo:
    volumes:
      - ../mongoData:/data/db
  core:
    environment:
      DEBUG: true
      WORKERS: 1
      FRONTEND_URL: http://localhost:8000
    volumes:
      - ./static:/root/brick-server-playground/static
      - ./app_static:/root/brick-server-playground/app_static
      - ./brick_server/playground:/root/brick-server-playground/brick_server/playground
      - ../brick-server-minimal/brick_server/minimal:/root/brick-server-minimal/brick_server/minimal
      - ./tests:/root/brick-server-playground/tests
      - ./benchmark:/root/brick-server-playground/benchmark
