version: '3.5'
services:
#  mongo:
#    image: mongo:5.0-focal
  core:
    environment:
      DEBUG: true
      WORKERS: 1
#      FRONTEND_URL: http://localhost:8000
    volumes:
      - ./static:/root/sbos-playground/static
      - ./sbos/playground:/root/sbos-playground/sbos/playground
      - ../sbos-minimal/sbos/minimal:/root/sbos-minimal/sbos/minimal
      - ./tests:/root/sbos-playground/tests
      - ./benchmark:/root/sbos-playground/benchmark
