version: '3.5'
services:
  core:
    environment:
      DEBUG: true
      WORKERS: 1
      FRONTEND_URL: http://localhost:8000
    volumes:
      - ./static:/root/brick-server-playground/static
      - ./brick_server/playground:/root/brick-server-playground/brick_server/playground
      - ../brick-server-minimal/brick_server/minimal:/root/brick-server-minimal/brick_server/minimal
      - ./tests:/root/brick-server-playground/tests
      - ./benchmark:/root/brick-server-playground/benchmark
