theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
#    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - toc.follow
#    - toc.integrate
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to system preference
site_name: SBOS Playground
docs_dir: docs
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
#      auto_title: true
#      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.magiclink
plugins:
  - include-markdown
not_in_nav: /generated/**/*.md
nav:
  - Home: index.md
  - Getting started:
      - Deployment: deployment.md
      - Initialization: init.md
      - Configuration:
          - config/index.md
          - Database: config/db.md
          - Authorization: config/auth.md
          - Backend: config/backend.md
  - Tutorials:
      - Tutorial@CPSIoT25!: tutorial/cpsiot25.md
      - Write a Brick based building app: tutorial/write_an_app.md
