version: '3.5'
services:
  sbos-postgres:
    container_name: sbos-postgres
    image: timescale/timescaledb-postgis:latest-pg13
    environment: # Below secrets should be matched with the information in `.env` too.
      - POSTGRES_USER=bricker
      - POSTGRES_PASSWORD=brick-demo
      - POSTGRES_DB=brick
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - sbos-network
    ports:
      - "35432:5432"
    volumes:
      - type: bind
        source: ./docker/init_postgis.sh
        target: /docker-entrypoint-initdb.d/003_init_postgis.sh
        read_only: true
      - ../psqlData:/var/lib/postgresql/data # change the path to yours accordingly
  sbos-graphdb:
    container_name: sbos-graphdb
    image: w1zzard/graphdb-free:9.9.0
    networks:
      - sbos-network
    ports:
      - "37200:7200"
  sbos-mongo:
    container_name: sbos-mongo
    image: mongo:4.2.3-bionic
    networks:
      - sbos-network
    ports:
      - "37017:27017"
  sbos-redis:
    container_name: sbos-redis
    image: 'redis:5.0.8'
    command: redis-server --requirepass brick-demo
    networks:
      - sbos-network
    ports:
      - "36379:6379"
  sbos:
    container_name: sbos
    image: sbos:minimal
    restart: on-failure
    volumes:
      - ./sbos:/root/sbos
      - ./tests:/root/tests
      - ./examples:/root/examples
      - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
    ports:
      - "9000:9000"
    networks:
      - sbos-network
      - isolated_nw
    environment:
      - DEBUG=true
      - HOST=sbos
      - MONGO_HOST=sbos-mongo
      - TIMESCALE_HOST=sbos-postgres
      - BRICK_HOST=sbos-virtuoso
      - GRAPHDB_HOST=sbos-graphdb
      - OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID}
      - OAUTH_GOOGLE_CLIENT_SECRET=${OAUTH_GOOGLE_CLIENT_SECRET}
    #      - GRAFANA_HOST=sbos-grafana
    depends_on:
      - sbos-graphdb
    privileged: true
    command: dockerize -wait http://sbos-graphdb:7200/rest/repositories python3 -m sbos.minimal
#    entrypoint: /app/docker/start-reload.sh

networks:
  sbos-network:
  isolated_nw:
