#!/usr/bin/env python

import json
import yaml
import time
import sys
from pdb import set_trace as bp
import jwt
sys.path.append("./brick-server-minimal")
sys.path.append("./")

from brick_server.models import get_doc
from playground.models import MarketApp, User, StagedApp

app_names = ['bacnet_driver', 'app1', 'genie']

if __name__ == '__main__':
    user_id = sys.argv[1]
    user = get_doc(User, user_id=user_id)
    for app_name in app_names:
        app = get_doc(StagedApp, name=app_name)
        if app not in user.activated_apps:
            user.activated_apps.append(app)
    user.save()
