version: '3.5'
services:
  playground-postgres:
    container_name: playground-postgres
    image: jbkoh/brickserver-postgresql:latest
    environment: # Below secrets should be matched with the information in `configs.json` too.
      - POSTGRES_USER=bricker
      - POSTGRES_PASSWORD=brick-demo
      - POSTGRES_DB=brick
    networks:
      - playground-backend-network

  playground-virtuoso:
    container_name: playground-virtuoso
    image: tenforce/virtuoso:virtuoso7.2.5
    environment:
      - SPARQL_UPDATE=true
    networks:
      - playground-backend-network

  playground-mongo:
    container_name: playground-mongo
    image: mongo:4.2.3-bionic
    networks:
      - playground-backend-network
  playground-redis:
    container_name: playground-redis
    image: 'redis:5.0.8'
    command: redis-server --requirepass brick-demo
    networks:
      - playground-backend-network
    #ports:
    #  - '127.0.0.6379:6379'

#  playground:
#    container_name: playground
#    image: jbkoh/playground:0.1
#    volumes:
#      #- ./configs/configs.json:/app/configs/configs.json
#      - /etc/letsencrypt/:/etc/letsencrypt/
#      - ./configs:/app/configs
#    ports:
#      - 8000:80
#    networks:
#      - playground-backend-network
#    environment:
#      - CERTFILE=/etc/letsencrypt/live/bd-testbed.ucsd.edu/fullchain.pem
#      - KEYFILE=/etc/letsencrypt/live/bd-testbed.ucsd.edu/privkey.pem
#      - ENABLE_SSL=true
#    command: >
#      /bin/bash -c "
#        sleep 10;
#        /app/docker/start.sh
#      "

networks:
  playground-backend-network:
    external: true
