#!/usr/bin/env python
import json
import sys
import time

import jwt

sys.path.append("./brick-server-minimal")

from brick_server.auth.authorization import create_jwt_token

with open("configs/configs.json") as fp:
    configs = json.load(fp)

with open(configs["auth"]["jwt"]["privkey_path"]) as fp:
    _jwt_priv_key = fp.read()
with open(configs["auth"]["jwt"]["pubkey_path"]) as fp:
    _jwt_pub_key = fp.read()

if __name__ == "__main__":
    if len(sys.argv) > 1:
        token_lifetime = int(sys.argv[1])
        print(token_lifetime)
    else:
        token_lifetime = 3600
    if len(sys.argv) == 3:
        user_name = sys.argv[2]
    else:
        user_name = "admin"
    # print(create_jwt_token(user_id='jbkoh@eng.ucsd.edu',
    print(
        create_jwt_token(
            user_id=user_name,
            app_name="brickserver_frontend",
            token_lifetime=token_lifetime,
        ).decode("utf-8")
    )
    # print(create_jwt_token(3600*24*365).decode('utf-8'))
