# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import iptables_manager_pb2 as iptables__manager__pb2


class IptablesManagerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateChain = channel.unary_unary(
        '/IptablesManager/CreateChain',
        request_serializer=iptables__manager__pb2.Cname.SerializeToString,
        response_deserializer=iptables__manager__pb2.Response.FromString,
        )
    self.DeleteChain = channel.unary_unary(
        '/IptablesManager/DeleteChain',
        request_serializer=iptables__manager__pb2.Cname.SerializeToString,
        response_deserializer=iptables__manager__pb2.Response.FromString,
        )
    self.GrantExternalAccess = channel.unary_unary(
        '/IptablesManager/GrantExternalAccess',
        request_serializer=iptables__manager__pb2.ExternalAccessRequest.SerializeToString,
        response_deserializer=iptables__manager__pb2.Response.FromString,
        )
    self.RevokeExternalAccess = channel.unary_unary(
        '/IptablesManager/RevokeExternalAccess',
        request_serializer=iptables__manager__pb2.ExternalAccessRequest.SerializeToString,
        response_deserializer=iptables__manager__pb2.Response.FromString,
        )
    self.GrantHostAccess = channel.unary_unary(
        '/IptablesManager/GrantHostAccess',
        request_serializer=iptables__manager__pb2.HostAccessRequest.SerializeToString,
        response_deserializer=iptables__manager__pb2.Response.FromString,
        )
    self.RevokeHostAccess = channel.unary_unary(
        '/IptablesManager/RevokeHostAccess',
        request_serializer=iptables__manager__pb2.HostAccessRequest.SerializeToString,
        response_deserializer=iptables__manager__pb2.Response.FromString,
        )
    self.RevokeAllAccess = channel.unary_unary(
        '/IptablesManager/RevokeAllAccess',
        request_serializer=iptables__manager__pb2.RevokeAllRequest.SerializeToString,
        response_deserializer=iptables__manager__pb2.Response.FromString,
        )


class IptablesManagerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateChain(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteChain(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GrantExternalAccess(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RevokeExternalAccess(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GrantHostAccess(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RevokeHostAccess(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RevokeAllAccess(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IptablesManagerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateChain': grpc.unary_unary_rpc_method_handler(
          servicer.CreateChain,
          request_deserializer=iptables__manager__pb2.Cname.FromString,
          response_serializer=iptables__manager__pb2.Response.SerializeToString,
      ),
      'DeleteChain': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteChain,
          request_deserializer=iptables__manager__pb2.Cname.FromString,
          response_serializer=iptables__manager__pb2.Response.SerializeToString,
      ),
      'GrantExternalAccess': grpc.unary_unary_rpc_method_handler(
          servicer.GrantExternalAccess,
          request_deserializer=iptables__manager__pb2.ExternalAccessRequest.FromString,
          response_serializer=iptables__manager__pb2.Response.SerializeToString,
      ),
      'RevokeExternalAccess': grpc.unary_unary_rpc_method_handler(
          servicer.RevokeExternalAccess,
          request_deserializer=iptables__manager__pb2.ExternalAccessRequest.FromString,
          response_serializer=iptables__manager__pb2.Response.SerializeToString,
      ),
      'GrantHostAccess': grpc.unary_unary_rpc_method_handler(
          servicer.GrantHostAccess,
          request_deserializer=iptables__manager__pb2.HostAccessRequest.FromString,
          response_serializer=iptables__manager__pb2.Response.SerializeToString,
      ),
      'RevokeHostAccess': grpc.unary_unary_rpc_method_handler(
          servicer.RevokeHostAccess,
          request_deserializer=iptables__manager__pb2.HostAccessRequest.FromString,
          response_serializer=iptables__manager__pb2.Response.SerializeToString,
      ),
      'RevokeAllAccess': grpc.unary_unary_rpc_method_handler(
          servicer.RevokeAllAccess,
          request_deserializer=iptables__manager__pb2.RevokeAllRequest.FromString,
          response_serializer=iptables__manager__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'IptablesManager', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
