#!/usr/bin/env python

import asyncio
import json
import sys
import time
from pdb import set_trace as bp

import jwt
import yaml
from rdflib import URIRef

sys.path.append("./brick-server-minimal")
sys.path.append("./")

from brick_server.dbs import brick_sparql_sync
from brick_server.models import get_doc
from playground.models import MarketApp, StagedApp, User


def add_user_room(user, room):
    brick_sparql_sync.add_triple(URIRef(user), "brick:hasOffice", URIRef(room))


if __name__ == "__main__":
    print(sys.argv)
    user_id = sys.argv[1]
    add_user_room(user_id, "bldg:RM101")
