version: '3.5'
services:
  postgres:
    image: timescale/timescaledb-postgis:latest-pg13
    environment: # Below secrets should be matched with the information in `.env` too.
      - POSTGRES_USER=bricker
      - POSTGRES_PASSWORD=brick-demo
      - POSTGRES_DB=brick
      - PGDATA=/var/lib/postgresql/data/pgdata
      - |
        INIT_POSTGIS=
        #!/bin/bash
        psql -U $$POSTGRES_USER $$POSTGRES_DB -c "CREATE EXTENSION IF NOT EXISTS postgis CASCADE;"
    networks:
      - sbos-network
    ports:
      - "35432:5432"
    command: /bin/bash -c "echo \"$$INIT_POSTGIS\" > /docker-entrypoint-initdb.d/002_init_postgis.sh; docker-entrypoint.sh postgres;"
  graphdb:
    image: w1zzard/graphdb-free:9.9.0
    networks:
      - sbos-network
    ports:
      - "37200:7200"
  mongo:
    image: mongo:4.2.3-bionic
    networks:
      - sbos-network
    ports:
      - "37017:27017"
  redis:
    image: 'redis:5.0.8'
    command: redis-server --requirepass brick-demo
    networks:
      - sbos-network
    ports:
      - "36379:6379"
  core:
    image: tcimba/sbos:playground
    build:
      context: ..
      dockerfile: ./sbos-playground/Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/root/sbos-playground/benchmark
    ports:
      - "9000:9000"
    networks:
      - sbos-network
      - isolated_nw
    environment:
      - DEBUG=true
      - HOST=0.0.0.0
      - MONGO_HOST=mongo
      - TIMESCALE_HOST=postgres
      - BRICK_HOST=virtuoso
      - GRAPHDB_HOST=graphdb
      - REDIS_HOST=redis
      - ISOLATED_NETWORK_NAME=sbos-playground_isolated_nw
      - WORKERS=${WORKERS:-1}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-}
      - CACHE=${CACHE:-true}
#      - GRAFANA_HOST=grafana
    depends_on:
      - graphdb
    privileged: true
    command: dockerize -wait http://graphdb:7200/rest/repositories python3 -m sbos.playground
#    entrypoint: /app/docker/start-reload.sh
  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=brick-demo
    networks:
      - sbos-network
    ports:
      - "38081:8081"

networks:
  sbos-network:
  isolated_nw:
