#!/usr/bin/env python
import sys
import jwt
from pdb import set_trace as bp
import arrow
sys.path.append("./brick-server-minimal")
sys.path.append("./")

from brick_server.models import User

if not User.objects(user_id='admin'):
    user = User(
        userid='admin',
        name='admin',
        is_admin=True,
        is_approved=True,
        registration_time=arrow.get().datetime,
        email='dummy@example.commm',
    )
    user.save()
