#!/usr/bin/env python
import sys
import jwt
from pdb import set_trace as bp
import arrow
sys.path.append("./brick-server-minimal")
sys.path.append("./")

from brick_server.auth.authorization import FRONTEND_APP
from playground.models import App, User

users = User.objects(userid='admin')
if not users:
    user = User(
        userid='admin',
        name='admin',
        is_admin=True,
        is_approved=True,
        registration_time=arrow.get().datetime,
        email='dummy@example.commm',
        installed_apps=[],
    )
    user.save()
else:
    user = users[0]

apps = App.objects(name=FRONTEND_APP)
if not apps:
    app = App(
        name=FRONTEND_APP,
        app_id=FRONTEND_APP,
    )
    app.save()
else:
    app = apps[0]

if app not in user.installed_apps:
    user.installed_apps.append(app)
    user.save()
