# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iptables_manager.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='iptables_manager.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16iptables_manager.proto\"\x1f\n\x05\x43name\x12\x16\n\x0e\x63ontainer_name\x18\x01 \x01(\t\":\n\x10RevokeAllRequest\x12\x16\n\x0e\x63ontainer_name\x18\x01 \x01(\t\x12\x0e\n\x06option\x18\x02 \x01(\x05\"\x1a\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\x05\"y\n\x15\x45xternalAccessRequest\x12\x16\n\x0e\x63ontainer_name\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontainer_ip\x18\x02 \x01(\t\x12\x10\n\x08protocol\x18\x03 \x01(\t\x12\x0e\n\x06\x64st_ip\x18\x04 \x01(\t\x12\x10\n\x08\x64st_port\x18\x05 \x01(\t\"e\n\x11HostAccessRequest\x12\x16\n\x0e\x63ontainer_name\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontainer_ip\x18\x02 \x01(\t\x12\x10\n\x08protocol\x18\x03 \x01(\t\x12\x10\n\x08\x64st_port\x18\x04 \x01(\t2\xee\x02\n\x0fIptablesManager\x12\"\n\x0b\x43reateChain\x12\x06.Cname\x1a\t.Response\"\x00\x12\"\n\x0b\x44\x65leteChain\x12\x06.Cname\x1a\t.Response\"\x00\x12:\n\x13GrantExternalAccess\x12\x16.ExternalAccessRequest\x1a\t.Response\"\x00\x12;\n\x14RevokeExternalAccess\x12\x16.ExternalAccessRequest\x1a\t.Response\"\x00\x12\x32\n\x0fGrantHostAccess\x12\x12.HostAccessRequest\x1a\t.Response\"\x00\x12\x33\n\x10RevokeHostAccess\x12\x12.HostAccessRequest\x1a\t.Response\"\x00\x12\x31\n\x0fRevokeAllAccess\x12\x11.RevokeAllRequest\x1a\t.Response\"\x00\x62\x06proto3')
)




_CNAME = _descriptor.Descriptor(
  name='Cname',
  full_name='Cname',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='container_name', full_name='Cname.container_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=57,
)


_REVOKEALLREQUEST = _descriptor.Descriptor(
  name='RevokeAllRequest',
  full_name='RevokeAllRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='container_name', full_name='RevokeAllRequest.container_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='option', full_name='RevokeAllRequest.option', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=117,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='Response.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=145,
)


_EXTERNALACCESSREQUEST = _descriptor.Descriptor(
  name='ExternalAccessRequest',
  full_name='ExternalAccessRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='container_name', full_name='ExternalAccessRequest.container_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='container_ip', full_name='ExternalAccessRequest.container_ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='protocol', full_name='ExternalAccessRequest.protocol', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dst_ip', full_name='ExternalAccessRequest.dst_ip', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dst_port', full_name='ExternalAccessRequest.dst_port', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=268,
)


_HOSTACCESSREQUEST = _descriptor.Descriptor(
  name='HostAccessRequest',
  full_name='HostAccessRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='container_name', full_name='HostAccessRequest.container_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='container_ip', full_name='HostAccessRequest.container_ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='protocol', full_name='HostAccessRequest.protocol', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dst_port', full_name='HostAccessRequest.dst_port', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=371,
)

DESCRIPTOR.message_types_by_name['Cname'] = _CNAME
DESCRIPTOR.message_types_by_name['RevokeAllRequest'] = _REVOKEALLREQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['ExternalAccessRequest'] = _EXTERNALACCESSREQUEST
DESCRIPTOR.message_types_by_name['HostAccessRequest'] = _HOSTACCESSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Cname = _reflection.GeneratedProtocolMessageType('Cname', (_message.Message,), {
  'DESCRIPTOR' : _CNAME,
  '__module__' : 'iptables_manager_pb2'
  # @@protoc_insertion_point(class_scope:Cname)
  })
_sym_db.RegisterMessage(Cname)

RevokeAllRequest = _reflection.GeneratedProtocolMessageType('RevokeAllRequest', (_message.Message,), {
  'DESCRIPTOR' : _REVOKEALLREQUEST,
  '__module__' : 'iptables_manager_pb2'
  # @@protoc_insertion_point(class_scope:RevokeAllRequest)
  })
_sym_db.RegisterMessage(RevokeAllRequest)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'iptables_manager_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

ExternalAccessRequest = _reflection.GeneratedProtocolMessageType('ExternalAccessRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXTERNALACCESSREQUEST,
  '__module__' : 'iptables_manager_pb2'
  # @@protoc_insertion_point(class_scope:ExternalAccessRequest)
  })
_sym_db.RegisterMessage(ExternalAccessRequest)

HostAccessRequest = _reflection.GeneratedProtocolMessageType('HostAccessRequest', (_message.Message,), {
  'DESCRIPTOR' : _HOSTACCESSREQUEST,
  '__module__' : 'iptables_manager_pb2'
  # @@protoc_insertion_point(class_scope:HostAccessRequest)
  })
_sym_db.RegisterMessage(HostAccessRequest)



_IPTABLESMANAGER = _descriptor.ServiceDescriptor(
  name='IptablesManager',
  full_name='IptablesManager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=374,
  serialized_end=740,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateChain',
    full_name='IptablesManager.CreateChain',
    index=0,
    containing_service=None,
    input_type=_CNAME,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteChain',
    full_name='IptablesManager.DeleteChain',
    index=1,
    containing_service=None,
    input_type=_CNAME,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GrantExternalAccess',
    full_name='IptablesManager.GrantExternalAccess',
    index=2,
    containing_service=None,
    input_type=_EXTERNALACCESSREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RevokeExternalAccess',
    full_name='IptablesManager.RevokeExternalAccess',
    index=3,
    containing_service=None,
    input_type=_EXTERNALACCESSREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GrantHostAccess',
    full_name='IptablesManager.GrantHostAccess',
    index=4,
    containing_service=None,
    input_type=_HOSTACCESSREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RevokeHostAccess',
    full_name='IptablesManager.RevokeHostAccess',
    index=5,
    containing_service=None,
    input_type=_HOSTACCESSREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RevokeAllAccess',
    full_name='IptablesManager.RevokeAllAccess',
    index=6,
    containing_service=None,
    input_type=_REVOKEALLREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IPTABLESMANAGER)

DESCRIPTOR.services_by_name['IptablesManager'] = _IPTABLESMANAGER

# @@protoc_insertion_point(module_scope)
